eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
logging:
  level:
    com.holland.gateway.filter.GatewayFilter: debug
    com.holland.gateway.filter.CustomWebFilterChain: debug
    com.holland.gateway.mapper.RouteWhitelistMapper: debug
spring:
  redis:
    host: 11.101.2.195
    port: 6379
    password: scxd@123
    token-timeout: 10
    token-key-prefix: "holland:"
  cache:
    redis:
      use-key-prefix: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/config
    username: postgres
    password: postgres