server:
  port: 8762
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: gateway
  profiles:
    active: dev
#    include: admin
  cloud:
    gateway:
      httpclient:
        connect-timeout: 200
        response-timeout: PT20S
        pool:
          max-idle-time: PT10S
          eviction-interval: PT30S
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true