server:
  port: 8762
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: gateway
  profiles:
    active: dev
    include: admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true