eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@114.115.212.83:8761/eureka/
logging:
  level:
    com.holland.gateway.filter.CustomWebFilterChain: debug
    com.holland.gateway.filter.AuthCheckFilter: debug
    com.holland.gateway.mapper: debug
    com.holland.nacos.conf.NacosPropKit: debug
    com.holland.kafka.Producer: debug
spring:
  redis:
    host: 114.115.212.83
    port: 6379
    # MINUTES
    token-timeout: 60
    token-key-prefix: "token_to_user:"
    user-key-prefix: "login_name_to_token:"
  cache:
    redis:
      use-key-prefix: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.115.212.83:3306/spring-cloud_gateway?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      config:
        server-addr: 114.115.212.83:8848
        group: DEFAULT_GROUP
        namespace: e45ec5af-12d8-4b45-a1f4-5eea3cf7a816
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
kafka:
  server: 114.115.212.83:9092
  groupId: ${spring.application.name}