eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
logging:
  level:
    com.holland.gateway.filter.CustomWebFilterChain: debug
    com.holland.gateway.mapper: debug
    com.holland.kafka.Producer: debug
spring:
  redis:
    host: localhost
    port: 6379
    # MINUTES
    token-timeout: 60
    token-key-prefix: "token_to_user:"
    user-key-prefix: "login_name_to_token:"
  cache:
    redis:
      use-key-prefix: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud_gateway?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
kafka:
  server: localhost:9092
  groupId: ${spring.application.name}