server:
  port: 8762
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: gateway
  profiles:
    active: dev
    include: admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
logging:
  level:
    com.holland.gateway.mapper.LogMapper.insertSelective: info
    com.holland.gateway.mapper.LogLoginMapper.insertSelective: info