server:
  port: 8762
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: stardon-main
          uri: http://localhost:8701
          predicates:
            - Path=/stardon-main/**
        - id: file-system
          uri: http://localhost:8763
          predicates:
            - Path=/filesystem/**