eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
hadoop:
  url: hdfs://11.101.4.89:9000
logging:
  level:
    org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferClient: error
