server:
  port: 8761
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
  profiles:
    include: admin
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/