server:
  port: 8761
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
  profiles:
    include: admin
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/