server:
  port: 8761
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/