spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://119.23.68.6:5432/config
    username: postgres
    password: 8DFn32P@$*,e!6
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
