spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yjg
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://root:root@11.101.2.195:8761/eureka/