spring:
  data:
    mongodb:
      uri: mongodb://119.23.68.6:27017/admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://119.23.68.6:5432/yjg
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: http://119.23.68.6:8761/eureka/