spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yjg
    username: postgres
    password: 8DFn32P@$*,e!6
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/