spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/config
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/